# Generated by Django 5.1.4 on 2025-01-11 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="wallet_address",
            field=models.CharField(
                blank=False, max_length=256, null=False, verbose_name="지갑 주소"
            ),
        ),
    ]
