# Generated by Django 5.1.4 on 2025-01-11 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=256, verbose_name="상점 이름")),
                (
                    "store_type",
                    models.CharField(
                        choices=[("private", "개인"), ("public", "공개")],
                        default="public",
                        max_length=16,
                        verbose_name="상점 종류",
                    ),
                ),
                (
                    "wallet_address",
                    models.CharField(max_length=256, verbose_name="지갑 주소"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
