# Generated by Django 5.1.4 on 2025-01-11 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="store",
            old_name="created",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="store",
            old_name="modified",
            new_name="modified_at",
        ),
    ]
