# Generated by Django 5.1.4 on 2025-01-11 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0002_rename_created_store_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="store",
            name="modified_at",
        ),
        migrations.AddField(
            model_name="store",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="수정 일시"),
        ),
        migrations.AlterField(
            model_name="store",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="생성 일시"),
        ),
    ]
