# Generated by Django 5.1.4 on 2025-01-11 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0004_userstorerelease"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="store",
            name="store_type",
        ),
        migrations.AddField(
            model_name="store",
            name="address",
            field=models.CharField(
                blank=False, max_length=256, null=False, verbose_name="주소"
            ),
        ),
        migrations.CreateModel(
            name="Prepay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정 일시"),
                ),
                ("credit", models.BigIntegerField(verbose_name="금액")),
                (
                    "code",
                    models.CharField(
                        blank=True, max_length=128, null=True, verbose_name="결제 코드"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("private", "개인"), ("public", "공개")],
                        default="public",
                        max_length=16,
                        verbose_name="공개 종류",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stores.store",
                        verbose_name="상점",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
